version: '3.8'

services:
  db:
    image: postgres:15
    container_name: usermanager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usermanager_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yml:/app/config.yml
    environment:
      CONFIG_PATH: /app/config.yml
    restart: unless-stopped

volumes:
  postgres_data:
